name: gibsonify
description: Collect nutritional data using Gibson's method.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dropdown_plus: ^0.0.9
  equatable: ^2.0.3  # TODO: see if can delete
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  formz: ^0.4.0 # TODO: see if can delete
  intl: ^0.17.0
  uuid: ^3.0.5  # TODO: see if can delete
  flutter_slidable: any
  gibsonify_api:
    path: packages/gibsonify_api
  gibsonify_repository:
    path: packages/gibsonify_repository
  path_provider: ^2.0.8
  flutter_mailer: ^2.0.0
  geolocator: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  bloc_test: ^9.0.2
  # TODO mocktail: ^0.1.4 or mockito???
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true
  remove_alpha_ios: true
